// apps/next-app/app/cms/page.tsx
'use client';

import React, { useState } from 'react';
import { GeinsCore } from '@geins/core';
import type { GeinsAPILocalization } from '@geins/types';
import { GeinsCMS } from '@geins/cms';

const Home = () => {
  const [items, setItems] = useState<string[]>([]);
  const localization: GeinsAPILocalization = {
    channelId: process.env.NEXT_PUBLIC_CHANNEL_ID || '1|se',
    marketId: process.env.NEXT_PUBLIC_MARKET_ID || 'se',
    languageId: process.env.NEXT_PUBLIC_LANGUAGE_ID || 'sv-SE',
  };
  const geinsCore = new GeinsCore({
    apiKey: process.env.NEXT_PUBLIC_API_KEY || '00000',
    accountName: process.env.NEXT_PUBLIC_ACCOUNT_NAME || 'demogeins',
  });
  const geinsCMS = new GeinsCMS(geinsCore);

  const getContentArea = async () => {
    const response = await geinsCMS.content.area(
      'Frontpage',
      'The front page area',
      {},
      localization,
    );
    if (response.loading) {
      console.info('loading');
      return;
    }
    if (!response.data) {
      console.info('no data');
      return;
    }

    const data = response.data;
    setItems((prevItems) => [
      `${new Date().toISOString()} :: -----------------`,
      JSON.stringify(data),
      ...prevItems,
    ]);
  };

  const getPage = async () => {
    const response = await geinsCMS.content.page('om-oss', {}, localization);
    if (response.loading) {
      console.info('loading');
      return;
    }
    if (!response.data) {
      console.info('no data');
      return;
    }

    const data = response.data;
    setItems((prevItems) => [
      `${new Date().toISOString()} :: -----------------`,
      JSON.stringify(data),
      ...prevItems,
    ]);
  };

  return (
    <main>
      <h2>Next.js @geins/CMS Test</h2>
      <button onClick={getContentArea}>Get Content Area</button>
      <button onClick={getPage}>Get Page</button>
      <div>
        {items.map((item, index) => (
          <>
            <br />
            <code>{item}</code>
          </>
        ))}
      </div>
    </main>
  );
};

export default Home;

// apps/nuxt-app/pages/cms/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { GeinsCore } from '@geins/core';
import { GeinsCMS } from '@geins/cms';
import type {
  Channel,
  MerchantApiCredentials,
  MenuType,
  ContentAreaType,
} from '@geins/types';

const runtimeConfig = useRuntimeConfig();
const items = ref<any[]>([]);
const channel: Channel = {
  siteId: runtimeConfig.public.channel.siteId,
  siteTopDomain: runtimeConfig.public.channel.siteTopDomain,
};

const geinsCredentials: MerchantApiCredentials = {
  ...runtimeConfig.public.geins,
};

const languageId = runtimeConfig.public.defaultLanguage;
const marketId = runtimeConfig.public.defaultMarket;

const geinsCore = new GeinsCore(geinsCredentials, channel, {
  marketId,
  languageId,
});
const geinsCMS = new GeinsCMS(geinsCore);

const slug = ref<string>('hej');
const family = ref<string>('Frontpage');
const area = ref<string>('The front page area');
const menuLocation = ref<string>('main-desktop');

const menuData = ref<MenuType>();
const pageData = ref<ContentAreaType>();

const resetCompnentData = () => {
  menuData.value = undefined;
  pageData.value = undefined;
};

const getContentArea = () => {
  resetCompnentData();
  console.log(
    'getting content area with family:""',
    family.value,
    '"and area:""',
    area.value,
    '"',
  );
  geinsCMS.content.area(family.value, area.value).then((response) => {
    if (response.loading) {
      console.info('loading');
      return;
    }
    if (!response.data) {
      console.info('no data');
      return;
    }
    const data = response.data;
    items.value.unshift({
      header: `:: geinsCMS.content.area :: ----------------- :: [${new Date().toISOString()}]`,
      data: JSON.stringify(data),
    });
  });
  geinsCMS.content
    .areaParsed(family.value, area.value)
    .then((result) => {
      return result as ContentAreaType;
    })
    .then((contentArea) => {
      console.log('widgetArea:', contentArea);
      pageData.value = contentArea;
      items.value.unshift({
        header: `:: geinsCMS.content.areaParsed :: ----------------- :: [${new Date().toISOString()}]`,
        data: JSON.stringify(contentArea),
      });
    });
};

const getPage = () => {
  resetCompnentData();
  console.log('getting page with slug:', slug.value);

  geinsCMS.page.alias(slug.value).then((response) => {
    if (response.loading) {
      console.info('loading');
      return;
    }
    if (!response.data) {
      console.info('no data');
      return;
    }
    const data = response.data;
    items.value.unshift({
      header: `:: geinsCMS.page.alias :: ----------------- :: [${new Date().toISOString()}]`,
      data: JSON.stringify(data),
    });
  });
  geinsCMS.page
    .aliasParsed(slug.value)
    .then((result) => {
      return result as ContentAreaType;
    })
    .then((contentArea) => {
      console.log('widgetArea:', contentArea);
      pageData.value = contentArea;
      items.value.unshift({
        header: `:: geinsCMS.page.aliasParsed :: ----------------- :: [${new Date().toISOString()}]`,
        data: JSON.stringify(contentArea),
      });
    });
};

const getMenu = () => {
  resetCompnentData();
  console.log('getting menu at location slug:', menuLocation.value);

  geinsCMS.menu.location(menuLocation.value).then((response) => {
    if (response.loading) {
      console.info('loading');
      return;
    }
    if (!response.data) {
      console.info('no data');
      return;
    }
    const data = response.data;
    items.value.unshift({
      header: `:: geinsCMS.menu.locationParsed :: ----------------- :: [${new Date().toISOString()}]`,
      data: JSON.stringify(data),
    });
  });

  geinsCMS.menu
    .locationParsed(menuLocation.value)
    .then((result) => {
      return result as MenuType;
    })
    .then((menu) => {
      menuData.value = menu;
      items.value.unshift({
        header: `:: geinsCMS.menu.locationParsed :: ----------------- :: [${new Date().toISOString()}]`,
        data: JSON.stringify(menu),
      });
    });
};
</script>
<template>
  <div>
    <h2>Nuxt @geins/cms content</h2>
    <table>
      <tr>
        <td style="vertical-align: top">
          <table>
            <tr>
              <td>family:</td>
              <td>area:</td>
              <td></td>
            </tr>
            <tr>
              <td><input v-model="family" /></td>
              <td><input v-model="area" /></td>
              <td><button @click="getContentArea">Get Content Area</button></td>
            </tr>
            <tr>
              <td></td>
              <td>slug:</td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input v-model="slug" /></td>
              <td><button @click="getPage">Get Page</button></td>
            </tr>
            <tr>
              <td></td>
              <td>slug:</td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input v-model="menuLocation" /></td>
              <td><button @click="getMenu">Get Menu</button></td>
            </tr>
          </table>
          <div v-for="(item, index) in items" :key="index">
            <p>
              <b>{{ item.header }}</b
              ><br />
              <textarea
                v-model="item.data"
                style="border: 0; width: 600px; height: 300px"
              ></textarea>
            </p>
          </div>
        </td>
        <td></td>
        <td style="vertical-align: top">
          <Menu v-if="menuData" :menu="menuData" />
          <ContentArea
            v-if="pageData"
            :family="family"
            :area="area"
            :data="pageData"
          />
        </td>
      </tr>
    </table>
  </div>
</template>
